site_name: Sample Docs
theme:
  name: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            separate_signature: true
nav:
  - 홈: index.md
  - API: api.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
